# Stage 1: Build the application using maven
FROM maven:3.9.8-eclipse-temurin-17 AS build
WORKDIR /app
# Copy the whole project to the container
COPY . .
# Build the specific module
RUN mvn -B -pl category-service clean package -DskipTests

# Stage 2: Create the runtime image
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/category-service/target/*.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]
